s=input("enter the string to be sliced")
s2=input("enter the second string")
print(s[0:4])
print(s[6:7])
print(s[6:20])
print(s[:2])
print(s[8:])
print(s[:])
print(s[12:20])
if 'n' in s:
    print('found')
else:
    print('not found')
new=s.lower()
new1=new.capitalize()
new2=new1.replace(new1[4:10],s2[:10])
print(s)
print(new)
print(new1)
print(new2)
